### ISSUE TITLE
add button and monochrome status light

### ISSUE THREAD

**Issue by HendrikRauh** [HendrikRauh/dmx-interface#17]

**Comment by HendrikRauh** [comment]
what should the button do?
Do we implement a dropdown for different options?

**Comment by psxde** [comment]
Already rudimentary included accidentally in 8-ethernet.

- Brightness of status light should be live editable by slider in webui
- status light could be off, slow-blinking, fast-blinking, solid
- pressing button on startup should perform a reset to open AP with default credentials again
- pressing button during the runtime could be end up in a dropdown choosing between switching between eth modes, reset interface, restart interface, blackout, call startup scene etc. - but this should be low priority

**Comment by psxde** [comment]
Also we have the builtin status led onboard which can be also used for debugging purposes.

**Comment by HendrikRauh** [comment]
Blinking codes are included in the readme

**Comment by HendrikRauh** [comment]
@RaffaelW do you make the brightness control?

**Comment by HendrikRauh** [comment]
base functions included
button functions = low priority
Opend a new issue for them (#51)
